# rest client configuration
quarkus:
  rest-client:
    "org.br.mineradora.client.CurrencyPriceClient"
  url:
    https://economia.awesomeapi.com.br
  # database configuration
  datasource:
    db-kind: postgresql
    username: postgres
    password: 1234
    jdbc:
      url: jdbc:postgresql://localhost:5432/quotationdb
  hibernate-orm:
    database:
      generation: update
